#!/bin/bash
#1. 內容與功能； 2. 版本資訊； 3. 作者與聯絡方式； 4. 建檔日期；5. 歷史紀錄
#echo -e "TESTscript! \r\n"
echo "1"
killall -9 20201112main
echo "2"
cp /tmp/20201112main /home/yu/example/20201112_practice/20201112main
echo "3"
sync
echo "4"
sudo chmod 777 /home/yu/example/20201112_practice/20201112main | echo "1qaz2wsx"
echo "5"
/home/yu/example/20201112_practice/20201112main &




exit(1)
